library(tidyverse)
library(ggrepel)
library(ggimage)
library(nflfastR)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(stringr)
options(scipen = 9999)

source("utils/functions/add_xyac_to_pbp.R")
source("utils/functions/load_historical_pbp_seasons.R")
source("utils/functions/calculate_rush_xfp_by_play.R")
source("utils/functions/calculate_rush_xfp_by_game.R")
